/**
 * CEO Agent — AI-powered executive orchestrator
 *
 * Role: Chief Operating Officer.
 * Never analyzes raw data directly.
 * Delegates to agent results, merges responses, generates executive report.
 * Falls back to deterministic synthesis when Gemini is unavailable.
 */

import { callAI, parseAIResponse } from "./aiService";
import { ceoFallback } from "./fallbackEngine";
import type { AgentOutput, AgentName, PipelineLogEntry } from "./types";

export const CEO_SYSTEM_PROMPT = `You are the CEO and Chief Operating Officer of a business.

You have been provided with analysis reports from your department heads (Finance, Sales, Inventory, Marketing, Operations).
Synthesize these reports into a comprehensive executive briefing.

Return ONLY a valid JSON object. Do NOT include markdown code blocks.
The "summary" field MUST be a plain text paragraph of 3-4 clear sentences summarizing business performance. Do NOT put JSON objects or stringified JSON inside the "summary" field.

Return exactly this JSON structure:
{
  "summary": "Executive summary paragraph summarizing overall business health and key operational priorities.",
  "score": 40,
  "risks": [{"title": "Risk Title", "severity": "high|medium|low", "detail": "Risk description"}],
  "opportunities": [{"title": "Opportunity Title", "impact": "high|medium|low", "detail": "Opportunity description"}],
  "recommendations": [{"title": "Action Item", "priority": "urgent|high|medium|low", "category": "Finance|Inventory|Sales|Marketing|Operations", "description": "Action details"}],
  "confidence": 90,
  "warnings": ["Warning text"],
  "reasoning": "Brief synthesis reasoning"
}`;

export const CEO_AGENT_CONFIG = {
  name: "ceo" as AgentName,
  label: "CEO Agent",
  description: "Orchestrates all agents and synthesizes executive report",
  emoji: "🎯",
  color: "#9EFF00",
};

/**
 * Run the CEO Agent — synthesizes results from all other agents.
 */
export async function runCEOAgent(
  companyId: string,
  agentResults: { name: string; output: AgentOutput }[],
  log: PipelineLogEntry[],
): Promise<{
  output: AgentOutput;
  executionMode: "ai" | "fallback";
  executionTimeMs: number;
}> {
  const startTime = performance.now();
  let executionMode: "ai" | "fallback" = "fallback";

  const logEntry = (level: PipelineLogEntry["level"], message: string) =>
    log.push({ timestamp: new Date().toISOString(), level, agent: "ceo", message });

  try {
    if (agentResults.length === 0) {
      logEntry("warn", "No agent results to synthesize");
      return {
        output: ceoFallback([]),
        executionMode: "fallback",
        executionTimeMs: Math.round(performance.now() - startTime),
      };
    }

    const ceoPrompt = agentResults.map((r) =>
      `=== ${r.name.toUpperCase()} ===\n${JSON.stringify(r.output, null, 2)}`
    ).join("\n\n");

    logEntry("info", "Synthesizing agent results with AI...");

    const aiResult = await callAI(companyId, {
      systemPrompt: CEO_SYSTEM_PROMPT,
      userPrompt: `Synthesize the following department reports into an executive briefing:\n\n${ceoPrompt}`,
    });

    if (aiResult.success && aiResult.text) {
      const parsed = parseAIResponse<AgentOutput>(aiResult.text);
      const data = parsed?.data || parsed;
      if (data && (data.summary || typeof data.score === "number")) {
        executionMode = "ai";
        logEntry("success", "Executive report generated by AI");
        return {
          output: {
            ...data,
            score: clampScore(data.score ?? 85),
            confidence: clampScore(data.confidence ?? 95),
            risks: (data.risks ?? []).slice(0, 8),
            opportunities: (data.opportunities ?? []).slice(0, 8),
            recommendations: (data.recommendations ?? []).slice(0, 10),
            warnings: (data.warnings ?? []).slice(0, 5),
          },
          executionMode,
          executionTimeMs: Math.round(performance.now() - startTime),
        };
      }
    }

    // Fallback
    executionMode = "fallback";
    logEntry("info", "Using fallback synthesis for executive report");
    const agentOutputs = agentResults.map((r) => r.output);
    return {
      output: ceoFallback(agentOutputs),
      executionMode,
      executionTimeMs: Math.round(performance.now() - startTime),
    };
  } catch {
    logEntry("error", "CEO agent error, using fallback");
    return {
      output: ceoFallback(agentResults.map((r) => r.output)),
      executionMode: "fallback",
      executionTimeMs: Math.round(performance.now() - startTime),
    };
  }
}

function clampScore(n: number): number {
  return Math.max(0, Math.min(100, Math.round(n)));
}